<?php

namespace App\Support;

class SiteContentDefaults
{
    public static function homeContent(): array
    {
        return [
            'record_key' => 'main',
            'nav_home_id' => 'Beranda',
            'nav_home_en' => 'Home',
            'nav_about_id' => 'Tentang Kami',
            'nav_about_en' => 'About Us',
            'nav_services_id' => 'Layanan',
            'nav_services_en' => 'Services',
            'nav_portfolio_id' => 'Portofolio',
            'nav_portfolio_en' => 'Portfolio',
            'nav_contact_id' => 'Hubungi Kami',
            'nav_contact_en' => 'Contact Us',
            'hero_badge_id' => 'IT Solution Partner Sejak 2016',
            'hero_badge_en' => 'IT Solution Partner Since 2016',
            'hero_title_id' => 'Digitally Customize',
            'hero_title_en' => 'Digitally Customize',
            'hero_title_highlight_id' => 'Your Needs',
            'hero_title_highlight_en' => 'Your Needs',
            'hero_description_id' => 'Kami mengubah ide kompleks menjadi solusi teknologi presisi. Warastra Adhiguna siap menjadi "senjata" andalan untuk memajukan bisnis Anda.',
            'hero_description_en' => 'We transform complex ideas into precise technological solutions. Warastra Adhiguna is ready to be your reliable "weapon" to advance your business.',
            'hero_primary_button_id' => 'Jelajahi Layanan',
            'hero_primary_button_en' => 'Explore Services',
            'hero_secondary_button_id' => 'Lihat Portofolio',
            'hero_secondary_button_en' => 'View Portfolio',
            'hero_slide_1_url' => 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1920',
            'hero_slide_2_url' => 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=1920',
            'hero_slide_3_url' => 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=1920',
            'about_tag_id' => 'Profil Perusahaan',
            'about_tag_en' => 'Company Profile',
            'about_title_id' => 'Mengenal Warastra Adhiguna (WAn)',
            'about_title_en' => 'Getting to Know Warastra Adhiguna (WAn)',
            'about_description_id' => 'Didirikan oleh Angling Kusumandhita di Salatiga pada tahun 2016. Saat ini, tim WAn memiliki 6 anggota tetap yang solid dan telah berhasil mengerjakan puluhan proyek pengembangan perangkat lunak dari berbagai kota.',
            'about_description_en' => 'Founded by Angling Kusumandhita in Salatiga in 2016. Currently, the WAn team has 6 solid permanent members and has successfully completed dozens of software development projects from various cities.',
            'about_philosophy_title_id' => 'Filosofi "WAn" (One)',
            'about_philosophy_title_en' => '"WAn" (One) Philosophy',
            'about_philosophy_description_id' => 'Berarti satu; yang pertama, terdepan, dan satu hati dalam maksud serta tujuan.',
            'about_philosophy_description_en' => 'Means one; the first, the foremost, and of one heart in purpose and goal.',
            'about_meaning_title_id' => 'Warastra Adhiguna',
            'about_meaning_title_en' => 'Warastra Adhiguna',
            'about_meaning_description_id' => '<strong>Warastra</strong> berarti senjata panah, <strong>Adhiguna</strong> berarti memiliki peran besar. Kami berharap menjadi perusahaan yang berperan besar menggunakan Teknologi Informasi sebagai senjatanya.',
            'about_meaning_description_en' => '<strong>Warastra</strong> means arrow weapon, <strong>Adhiguna</strong> means having a great role. We hope to become a company that plays a major role using Information Technology as its weapon.',
            'about_image_url' => 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=800',
            'services_tag_id' => 'Layanan Kami',
            'services_tag_en' => 'Our Services',
            'services_title_id' => 'Solusi Teknologi Terintegrasi',
            'services_title_en' => 'Integrated Technology Solutions',
            'services_description_id' => 'Kami menawarkan berbagai layanan IT profesional untuk memastikan operasional bisnis Anda berjalan lancar, modern, dan efisien.',
            'services_description_en' => 'We offer various professional IT services to ensure your business operations run smoothly, modernly, and efficiently.',
            'portfolio_tag_id' => 'Karya Kami',
            'portfolio_tag_en' => 'Our Work',
            'portfolio_title_id' => 'Portofolio Pilihan',
            'portfolio_title_en' => 'Selected Portfolio',
            'portfolio_link_label_id' => 'Lihat Semua Proyek',
            'portfolio_link_label_en' => 'View All Projects',
            'portfolio_link_url' => '#',
            'contact_title_id' => 'Mari Berkolaborasi!',
            'contact_title_en' => 'Let\'s Collaborate!',
            'contact_description_id' => 'Punya ide bisnis atau membutuhkan solusi digital? Jangan ragu untuk menghubungi kami. Tim Warastra Adhiguna siap membantu mewujudkan visi Anda.',
            'contact_description_en' => 'Have a business idea or need a digital solution? Don\'t hesitate to contact us. The Warastra Adhiguna team is ready to help realize your vision.',
            'contact_phone_label_id' => 'Instagram',
            'contact_phone_label_en' => 'Instagram',
            'contact_email_label_id' => 'Email',
            'contact_email_label_en' => 'Email',
            'contact_location_label_id' => 'Lokasi',
            'contact_location_label_en' => 'Location',
            'contact_location_value_id' => 'Salatiga, Jawa Tengah',
            'contact_location_value_en' => 'Salatiga, Central Java',
            'contact_phone' => '@username_instagram',
            'contact_email' => 'warastra.adhiguna@gmail.com',
            'form_name_label_id' => 'Nama Lengkap',
            'form_name_label_en' => 'Full Name',
            'form_name_placeholder_id' => 'Masukkan nama Anda',
            'form_name_placeholder_en' => 'Enter your name',
            'form_email_label_id' => 'Email',
            'form_email_label_en' => 'Email',
            'form_email_placeholder_id' => 'nama@email.com',
            'form_email_placeholder_en' => 'name@email.com',
            'form_message_label_id' => 'Pesan / Kebutuhan',
            'form_message_label_en' => 'Message / Requirements',
            'form_message_placeholder_id' => 'Ceritakan proyek Anda...',
            'form_message_placeholder_en' => 'Tell us about your project...',
            'form_button_id' => 'Kirim Pesan',
            'form_button_en' => 'Send Message',
            'footer_rights_id' => 'All rights reserved.',
            'footer_rights_en' => 'All rights reserved.',
            'footer_tagline_id' => 'Digitally Customize Your Needs',
            'footer_tagline_en' => 'Digitally Customize Your Needs',
        ];
    }

    public static function services(): array
    {
        return [
            [
                'sort_order' => 1,
                'is_active' => true,
                'icon_class' => 'bi bi-lightbulb',
                'icon_color' => '#3b82f6',
                'title_id' => 'Konsultasi IT',
                'title_en' => 'IT Consulting',
                'description_id' => 'Pelayanan konsultasi komprehensif untuk Perangkat Lunak, Perangkat Keras, dan Jaringan Komputer.',
                'description_en' => 'Comprehensive consulting services for Software, Hardware, and Computer Networks.',
            ],
            [
                'sort_order' => 2,
                'is_active' => true,
                'icon_class' => 'bi bi-code-slash',
                'icon_color' => '#10b981',
                'title_id' => 'Software Development',
                'title_en' => 'Software Development',
                'description_id' => 'Pengembangan perangkat lunak kustom yang disesuaikan secara presisi dengan kebutuhan bisnis Anda.',
                'description_en' => 'Custom software development precisely tailored to your business needs.',
            ],
            [
                'sort_order' => 3,
                'is_active' => true,
                'icon_class' => 'bi bi-server',
                'icon_color' => '#8b5cf6',
                'title_id' => 'Client-Server System',
                'title_en' => 'Client-Server System',
                'description_id' => 'Perancangan dan implementasi arsitektur komputer Client-Server yang tangguh dan aman.',
                'description_en' => 'Design and implementation of a robust and secure Client-Server computer architecture.',
            ],
            [
                'sort_order' => 4,
                'is_active' => true,
                'icon_class' => 'bi bi-diagram-3',
                'icon_color' => '#0ea5e9',
                'title_id' => 'Network Implementation',
                'title_en' => 'Network Implementation',
                'description_id' => 'Perancangan dan implementasi infrastruktur Jaringan Komputer berkinerja tinggi.',
                'description_en' => 'Design and implementation of high-performance Computer Network infrastructure.',
            ],
        ];
    }

    public static function portfolioItems(): array
    {
        return [
            [
                'sort_order' => 1,
                'is_active' => true,
                'badge_id' => 'E-Commerce',
                'badge_en' => 'E-Commerce',
                'title_id' => 'Web E-Commerce',
                'title_en' => 'E-Commerce Web',
                'subtitle_id' => 'Wallbranding (Sidomulyo, Salatiga)',
                'subtitle_en' => 'Wallbranding (Sidomulyo, Salatiga)',
                'image_url' => 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=800',
                'project_url' => null,
            ],
            [
                'sort_order' => 2,
                'is_active' => true,
                'badge_id' => 'Platform Web',
                'badge_en' => 'Web Platform',
                'title_id' => 'IYES Business Incubator',
                'title_en' => 'IYES Business Incubator',
                'subtitle_id' => 'Salatiga',
                'subtitle_en' => 'Salatiga',
                'image_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
                'project_url' => null,
            ],
            [
                'sort_order' => 3,
                'is_active' => true,
                'badge_id' => 'Dashboard',
                'badge_en' => 'Dashboard',
                'title_id' => 'SIJITU',
                'title_en' => 'SIJITU',
                'subtitle_id' => 'Dashboard Peringkat Evaluasi 2021',
                'subtitle_en' => '2021 Evaluation Ranking Dashboard',
                'image_url' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
                'project_url' => null,
            ],
        ];
    }
}
